# Generated by Django 5.0.7 on 2025-04-25 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('archive_id', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('doc_type', models.CharField(blank=True, max_length=100, null=True)),
                ('project_path', models.CharField(max_length=500)),
                ('project_folder_name', models.CharField(max_length=255)),
                ('document_folder_path', models.CharField(blank=True, max_length=500, null=True)),
                ('document_folder_name', models.CharField(blank=True, max_length=255, null=True)),
                ('comlist_path', models.CharField(blank=True, max_length=500, null=True)),
                ('output_dir', models.CharField(blank=True, max_length=500, null=True)),
                ('has_document_folder', models.BooleanField(default=False)),
                ('is_document_folder', models.BooleanField(default=False)),
                ('processing_complete', models.BooleanField(default=False)),
                ('debug_mode', models.BooleanField(default=False)),
                ('retain_sources', models.BooleanField(default=True)),
                ('auto_detect_oversize', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workflow_mode', models.CharField(choices=[('manual', 'Manual'), ('semi-auto', 'Semi-Automatic'), ('auto', 'Automatic')], default='semi-auto', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
