# Generated by Django 5.0.7 on 2025-05-01 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='name',
        ),
        migrations.AddField(
            model_name='project',
            name='add_to_database',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='has_oversized',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='total_pages',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='total_pages_with_refs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='archive_id',
            field=models.CharField(help_text='Format: RRDxxx-xxxx', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='doc_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(help_text='Location code (e.g., OU, DW)', max_length=10),
        ),
    ]
