# Generated by Django 5.0.7 on 2025-05-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microapp', '0002_remove_project_name_project_add_to_database_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='debug_mode',
            new_name='has_pdf_folder',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='has_document_folder',
            new_name='has_source_folder',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='is_document_folder',
            new_name='is_source_folder',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='document_folder_path',
            new_name='pdf_folder_path',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='document_folder_name',
            new_name='source_folder_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='auto_detect_oversize',
        ),
        migrations.RemoveField(
            model_name='project',
            name='workflow_mode',
        ),
        migrations.AddField(
            model_name='project',
            name='source_folder_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
