# Generated by Django 5.0.7 on 2025-05-01 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microapp', '0003_rename_debug_mode_project_has_pdf_folder_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='has_source_folder',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_source_folder',
        ),
        migrations.RemoveField(
            model_name='project',
            name='source_folder_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='source_folder_path',
        ),
    ]
