# Generated by Django 5.0.7 on 2025-05-04 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microapp', '0005_project_data_dir_project_distribution_complete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roll',
            name='roll_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
