# Generated by Django 5.0.7 on 2025-05-04 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microapp', '0006_alter_roll_roll_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentreferenceinfo',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_info', to='microapp.document'),
        ),
    ]
