# Generated by Django 5.0.7 on 2025-05-07 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microapp', '0007_alter_documentreferenceinfo_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='archive_id',
            field=models.CharField(help_text='Format: RRDxxx-yyyy', max_length=20),
        ),
        migrations.CreateModel(
            name='AdjustedRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_start', models.IntegerField(help_text='Original start page')),
                ('original_end', models.IntegerField(help_text='Original end page')),
                ('adjusted_start', models.IntegerField(help_text='Adjusted start page after reference insertion')),
                ('adjusted_end', models.IntegerField(help_text='Adjusted end page after reference insertion')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjusted_ranges', to='microapp.document')),
            ],
            options={
                'ordering': ['document', 'original_start'],
            },
        ),
        migrations.CreateModel(
            name='DistributionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('DEBUG', 'Debug'), ('SUCCESS', 'Success')], max_length=10)),
                ('message', models.TextField()),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distribution_logs', to='microapp.document')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_logs', to='microapp.project')),
                ('roll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distribution_logs', to='microapp.roll')),
            ],
            options={
                'ordering': ['project', '-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DistributionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('output_dir', models.CharField(blank=True, max_length=500, null=True)),
                ('reference_sheets', models.IntegerField(default=0, help_text='Total reference sheets generated')),
                ('documents_with_references', models.IntegerField(default=0, help_text='Documents with reference sheets')),
                ('oversized_documents_extracted', models.IntegerField(default=0)),
                ('processed_35mm_documents', models.IntegerField(default=0)),
                ('copied_35mm_documents', models.IntegerField(default=0)),
                ('processed_16mm_documents', models.IntegerField(default=0)),
                ('copied_16mm_documents', models.IntegerField(default=0)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('partial', 'Partial Success')], default='success', max_length=20)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_result', to='microapp.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(help_text='Path to processed document file', max_length=500)),
                ('processing_type', models.CharField(choices=[('16mm_with_refs', '16mm with references'), ('35mm_with_refs', '35mm with references'), ('extracted_oversized', 'Extracted oversized pages'), ('standard', 'Standard document'), ('split', 'Split document')], max_length=20)),
                ('start_page', models.IntegerField(blank=True, help_text='Start page if this is a document segment', null=True)),
                ('end_page', models.IntegerField(blank=True, help_text='End page if this is a document segment', null=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('copied_to_output', models.BooleanField(default=False, help_text='Whether copied to output directory')),
                ('output_path', models.CharField(blank=True, help_text='Path in output directory', max_length=500, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_versions', to='microapp.document')),
                ('roll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processed_documents', to='microapp.roll')),
                ('segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processed_document', to='microapp.documentsegment')),
            ],
            options={
                'ordering': ['document', 'processing_type', 'start_page'],
            },
        ),
        migrations.CreateModel(
            name='ReferenceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range_start', models.IntegerField(help_text='Start page of oversized range')),
                ('range_end', models.IntegerField(help_text='End page of oversized range')),
                ('path', models.CharField(help_text='Path to reference sheet PDF', max_length=500)),
                ('blip_35mm', models.CharField(blank=True, help_text='Blip code for 35mm film', max_length=50, null=True)),
                ('film_number_35mm', models.CharField(blank=True, help_text='Film number for 35mm roll', max_length=50, null=True)),
                ('human_range', models.CharField(blank=True, help_text="Human-readable page range (e.g. '1 von 5')", max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_sheets', to='microapp.document')),
                ('document_range', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reference_sheet', to='microapp.documentrange')),
            ],
            options={
                'ordering': ['document', 'range_start'],
            },
        ),
        migrations.CreateModel(
            name='ReadablePageDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range_index', models.IntegerField(help_text="Index of the range in document's ranges")),
                ('description', models.CharField(help_text="Human-readable description e.g. '1 von 5'", max_length=100)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readable_page_descriptions', to='microapp.document')),
            ],
            options={
                'ordering': ['document', 'range_index'],
                'unique_together': {('document', 'range_index')},
            },
        ),
    ]
