# Generated by Django 5.1.7 on 2025-05-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microapp', '0008_alter_project_archive_id_adjustedrange_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roll',
            name='roll_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='DistributionLog',
        ),
    ]
