# Generated by Django 5.1.7 on 2025-05-23 16:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microapp', '0009_alter_roll_roll_id_delete_distributionlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('template', models.CharField(choices=[('16mm', '16mm'), ('35mm', '35mm')], help_text='Film template (16mm or 35mm)', max_length=10)),
                ('film_number', models.CharField(help_text='Film number for this session', max_length=50)),
                ('project_path', models.CharField(help_text='Path to project folder', max_length=500)),
                ('output_dir', models.CharField(help_text='Output directory path', max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('error', 'Error')], default='pending', max_length=20)),
                ('total_documents', models.IntegerField(default=0, help_text='Total documents to process')),
                ('processed_documents', models.IntegerField(default=0, help_text='Documents processed so far')),
                ('progress_percent', models.FloatField(default=0.0, help_text='Progress percentage (0-100)')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, help_text='Total session duration', null=True)),
                ('estimated_remaining', models.DurationField(blank=True, help_text='Estimated remaining time', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if session failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filming_sessions', to='microapp.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filming_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_id'], name='microapp_fi_session_9aed8b_idx'), models.Index(fields=['status'], name='microapp_fi_status_ca8591_idx'), models.Index(fields=['project', 'status'], name='microapp_fi_project_0b8346_idx')],
            },
        ),
    ]
