# Generated by Django 5.0.7 on 2025-05-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microapp', '0010_filmingsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='roll',
            name='output_directory',
            field=models.CharField(blank=True, help_text="Path to the roll's output directory where documents are distributed", max_length=500, null=True),
        ),
    ]
