# Generated by Django 5.0.7 on 2025-05-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microapp', '0011_roll_output_directory'),
    ]

    operations = [
        migrations.AddField(
            model_name='roll',
            name='filming_completed_at',
            field=models.DateTimeField(blank=True, help_text='When filming was completed for this roll', null=True),
        ),
        migrations.AddField(
            model_name='roll',
            name='filming_progress_percent',
            field=models.FloatField(default=0.0, help_text='Filming progress percentage (0-100)'),
        ),
        migrations.AddField(
            model_name='roll',
            name='filming_session_id',
            field=models.CharField(blank=True, help_text='ID of the current/last filming session', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='roll',
            name='filming_started_at',
            field=models.DateTimeField(blank=True, help_text='When filming started for this roll', null=True),
        ),
        migrations.AddField(
            model_name='roll',
            name='filming_status',
            field=models.CharField(choices=[('ready', 'Ready to Film'), ('filming', 'Currently Filming'), ('completed', 'Filming Completed'), ('error', 'Filming Error')], default='ready', help_text='Current filming status of this roll', max_length=20),
        ),
    ]
