# Generated by Django 5.1.7 on 2025-05-26 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microapp', '0012_add_roll_filming_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmingSessionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=10)),
                ('message', models.TextField(help_text='Log message content')),
                ('workflow_state', models.CharField(blank=True, help_text='Workflow state when log was created', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='filmingsession',
            name='estimated_remaining',
        ),
        migrations.RemoveField(
            model_name='filmingsession',
            name='film_number',
        ),
        migrations.RemoveField(
            model_name='filmingsession',
            name='output_dir',
        ),
        migrations.RemoveField(
            model_name='filmingsession',
            name='project_path',
        ),
        migrations.RemoveField(
            model_name='filmingsession',
            name='template',
        ),
        migrations.AddField(
            model_name='filmingsession',
            name='film_type',
            field=models.CharField(choices=[('16mm', '16mm'), ('35mm', '35mm')], default='16mm', help_text='Film type (16mm or 35mm)', max_length=10),
        ),
        migrations.AddField(
            model_name='filmingsession',
            name='recovery_mode',
            field=models.BooleanField(default=False, help_text='Whether this session is in recovery mode'),
        ),
        migrations.AddField(
            model_name='filmingsession',
            name='roll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filming_sessions', to='microapp.roll'),
        ),
        migrations.AddField(
            model_name='filmingsession',
            name='workflow_state',
            field=models.CharField(choices=[('initialization', 'Initialization'), ('monitoring', 'Independent Monitoring'), ('advanced_finish', 'Advanced Finish'), ('completed', 'Completed')], default='initialization', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='folder_path',
            field=models.CharField(blank=True, help_text='Main folder path for the project', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(blank=True, help_text='Project name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='roll',
            name='filmed_at',
            field=models.DateTimeField(blank=True, help_text='When this roll was filmed', null=True),
        ),
        migrations.AddField(
            model_name='roll',
            name='roll_number',
            field=models.CharField(blank=True, help_text='Roll number for this roll', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='filmingsession',
            name='session_id',
            field=models.CharField(help_text='Unique session identifier', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='filmingsession',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('terminated', 'Terminated')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='filmingsession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filming_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roll',
            name='status',
            field=models.CharField(default='active', help_text='Status of the roll (active, used, filmed, etc.)', max_length=20),
        ),
        migrations.AddIndex(
            model_name='filmingsession',
            index=models.Index(fields=['workflow_state'], name='microapp_fi_workflo_72889e_idx'),
        ),
        migrations.AddField(
            model_name='filmingsessionlog',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='microapp.filmingsession'),
        ),
        migrations.AddIndex(
            model_name='filmingsessionlog',
            index=models.Index(fields=['session', '-created_at'], name='microapp_fi_session_f8c05f_idx'),
        ),
        migrations.AddIndex(
            model_name='filmingsessionlog',
            index=models.Index(fields=['level'], name='microapp_fi_level_b55bed_idx'),
        ),
    ]
