# Generated by Django 5.1.7 on 2025-05-30 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microapp', '0013_filmingsessionlog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='roll',
            name='development_completed_at',
            field=models.DateTimeField(blank=True, help_text='When development was completed for this roll', null=True),
        ),
        migrations.AddField(
            model_name='roll',
            name='development_progress_percent',
            field=models.FloatField(default=0.0, help_text='Development progress percentage (0-100)'),
        ),
        migrations.AddField(
            model_name='roll',
            name='development_started_at',
            field=models.DateTimeField(blank=True, help_text='When development started for this roll', null=True),
        ),
        migrations.AddField(
            model_name='roll',
            name='development_status',
            field=models.CharField(choices=[('pending', 'Pending Development'), ('developing', 'Currently Developing'), ('completed', 'Development Completed'), ('failed', 'Development Failed')], default='pending', help_text='Current development status of this roll', max_length=20),
        ),
        migrations.CreateModel(
            name='ChemicalBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chemical_type', models.CharField(choices=[('developer', 'Developer'), ('fixer', 'Fixer'), ('cleaner1', 'Cleaner 1'), ('cleaner2', 'Cleaner 2')], max_length=20)),
                ('batch_id', models.CharField(help_text='Batch identifier', max_length=50)),
                ('max_area', models.FloatField(default=10.0, help_text='Maximum film area this batch can process (m²)')),
                ('used_area', models.FloatField(default=0.0, help_text='Film area already processed (m²)')),
                ('used_16mm_rolls', models.IntegerField(default=0, help_text='Number of 16mm rolls processed')),
                ('used_35mm_rolls', models.IntegerField(default=0, help_text='Number of 35mm rolls processed')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this batch is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('replaced_at', models.DateTimeField(blank=True, help_text='When this batch was replaced', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['chemical_type', 'is_active'], name='microapp_ch_chemica_655759_idx'), models.Index(fields=['is_active'], name='microapp_ch_is_acti_927753_idx')],
            },
        ),
        migrations.CreateModel(
            name='DevelopmentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='Unique development session identifier', max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Development'), ('developing', 'Currently Developing'), ('completed', 'Development Completed'), ('failed', 'Development Failed')], default='pending', max_length=20)),
                ('development_duration_minutes', models.IntegerField(default=30, help_text='Development duration in minutes')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_completion', models.DateTimeField(blank=True, null=True)),
                ('progress_percent', models.FloatField(default=0.0, help_text='Development progress percentage (0-100)')),
                ('chemical_usage_area', models.FloatField(default=0.0, help_text='Film area processed in m²')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('roll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='development_sessions', to='microapp.roll')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='development_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DevelopmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=10)),
                ('message', models.TextField(help_text='Log message content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='microapp.developmentsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='developmentsession',
            index=models.Index(fields=['session_id'], name='microapp_de_session_d35533_idx'),
        ),
        migrations.AddIndex(
            model_name='developmentsession',
            index=models.Index(fields=['status'], name='microapp_de_status_f12daf_idx'),
        ),
        migrations.AddIndex(
            model_name='developmentsession',
            index=models.Index(fields=['roll'], name='microapp_de_roll_id_b6c50e_idx'),
        ),
        migrations.AddIndex(
            model_name='developmentlog',
            index=models.Index(fields=['session', '-created_at'], name='microapp_de_session_f20271_idx'),
        ),
        migrations.AddIndex(
            model_name='developmentlog',
            index=models.Index(fields=['level'], name='microapp_de_level_2d9deb_idx'),
        ),
    ]
