# Generated by Django 5.1.7 on 2025-06-02 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microapp', '0014_roll_development_completed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DensityMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('density_value', models.FloatField(help_text='Measured density value (0.0 - 2.0)')),
                ('measurement_time_minutes', models.IntegerField(help_text='Time in minutes when measurement was taken (e.g., 10, 20, 30)')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the measurement', null=True)),
                ('is_within_optimal_range', models.BooleanField(default=False, help_text='Whether measurement is within optimal range (1.2-1.4)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='density_measurements', to='microapp.developmentsession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='density_measurements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['session', 'measurement_time_minutes'],
                'indexes': [models.Index(fields=['session', 'measurement_time_minutes'], name='microapp_de_session_b52abf_idx'), models.Index(fields=['density_value'], name='microapp_de_density_b3e5d4_idx'), models.Index(fields=['is_within_optimal_range'], name='microapp_de_is_with_74854b_idx')],
                'unique_together': {('session', 'measurement_time_minutes')},
            },
        ),
    ]
