# Generated by Django 5.1.7 on 2025-06-02 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microapp', '0015_densitymeasurement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_id', models.CharField(help_text='Unique label identifier', max_length=100, unique=True)),
                ('film_number', models.CharField(help_text='Film number on the label', max_length=50)),
                ('archive_id', models.CharField(help_text='Archive ID on the label', max_length=20)),
                ('doc_type', models.CharField(help_text='Document type on the label', max_length=50)),
                ('pdf_path', models.CharField(blank=True, help_text='Path to saved PDF file', max_length=500, null=True)),
                ('cache_key', models.CharField(blank=True, help_text='Cache key for temporary storage', max_length=100, null=True)),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('downloaded', 'Downloaded'), ('queued', 'Queued for Print'), ('printed', 'Printed'), ('completed', 'Completed')], default='generated', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('downloaded_at', models.DateTimeField(blank=True, help_text='When label was first downloaded', null=True)),
                ('queued_at', models.DateTimeField(blank=True, help_text='When label was added to print queue', null=True)),
                ('printed_at', models.DateTimeField(blank=True, help_text='When label was printed', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When label process was completed', null=True)),
                ('download_count', models.IntegerField(default=0, help_text='Number of times label was downloaded')),
                ('print_count', models.IntegerField(default=0, help_text='Number of times label was printed')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='film_labels', to='microapp.project')),
                ('roll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='film_labels', to='microapp.roll')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='film_labels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['label_id'], name='microapp_fi_label_i_d605f8_idx'), models.Index(fields=['roll', 'status'], name='microapp_fi_roll_id_55f887_idx'), models.Index(fields=['project', 'status'], name='microapp_fi_project_dae859_idx'), models.Index(fields=['status'], name='microapp_fi_status_8f8588_idx'), models.Index(fields=['generated_at'], name='microapp_fi_generat_d70a1d_idx')],
            },
        ),
    ]
