# Generated by Django 5.1.7 on 2025-06-05 00:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microapp', '0016_filmlabel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='filmlabel',
            name='version',
            field=models.CharField(choices=[('normal', 'Normal'), ('angled', 'Angled')], default='normal', help_text='Label version (normal or angled)', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='filmlabel',
            unique_together={('roll', 'version')},
        ),
        migrations.AddIndex(
            model_name='filmlabel',
            index=models.Index(fields=['roll', 'version'], name='microapp_fi_roll_id_7a693c_idx'),
        ),
    ]
