# Generated by Django 5.1.7 on 2025-07-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microapp', '0018_handoffrecord_handoffvalidationsnapshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='com_id',
            field=models.CharField(blank=True, help_text='COM ID from comlist Excel file', max_length=50, null=True),
        ),
    ]
