# Generated by Django 5.1.7 on 2025-07-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microapp', '0019_change_com_id_to_charfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='handoff_complete',
            field=models.BooleanField(default=False, help_text='Whether the project has been successfully handed off via email'),
        ),
    ]
