# Generated by Django 5.1.7 on 2025-07-31 15:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microapp', '0021_analyzedfolder'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemicalbatch',
            name='installation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When this batch was installed in the machine'),
        ),
        migrations.AddField(
            model_name='temproll',
            name='exists',
            field=models.BooleanField(default=False, help_text='Whether this temp roll physically exists (vs just planned)'),
        ),
    ]
