# Generated by Django 5.1.7 on 2025-08-01 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microapp', '0022_chemicalbatch_installation_date_temproll_exists'),
    ]

    operations = [
    ]
