# Generated by Django 5.1.7 on 2025-08-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microapp', '0023_add_temp_roll_fields_to_analyzed_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzedfolder',
            name='estimated_temp_rolls_created',
            field=models.IntegerField(default=0, help_text='Estimated number of temp rolls that would be created'),
        ),
        migrations.AddField(
            model_name='analyzedfolder',
            name='estimated_temp_rolls_used',
            field=models.IntegerField(default=0, help_text='Estimated number of existing temp rolls that would be used'),
        ),
        migrations.AddField(
            model_name='analyzedfolder',
            name='temp_roll_strategy',
            field=models.CharField(default='unknown', help_text='Strategy for temp roll usage (create, use, both, none)', max_length=20),
        ),
    ]
