# Generated by Django 5.1.7 on 2025-08-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microapp', '0024_add_temp_roll_fields_to_analyzed_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='roll',
            name='rework_requested',
            field=models.BooleanField(default=False, help_text='Whether this roll is flagged for re-filming/rework'),
        ),
    ]
