# Generated by Django 5.1.7 on 2025-08-12 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microapp', '0025_roll_rework_requested'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roll',
            name='rework_requested',
        ),
    ]
