# Generated by Django 5.1.7 on 2025-11-18 10:30

from django.db import migrations, models, connection


def add_constraints_if_not_exists(apps, schema_editor):
    """Add constraints only if they don't already exist."""
    with connection.cursor() as cursor:
        # Check if unique_film_number constraint exists
        if 'sqlite' in connection.vendor:
            cursor.execute("""
                SELECT name FROM sqlite_master 
                WHERE type='index' AND name=%s
            """, ['unique_film_number'])
            unique_film_number_exists = cursor.fetchone() is not None
            
            cursor.execute("""
                SELECT name FROM sqlite_master 
                WHERE type='index' AND name=%s
            """, ['unique_project_roll_id_film_type'])
            unique_project_roll_exists = cursor.fetchone() is not None
        else:
            # For other databases, assume they don't exist and let AddConstraint handle it
            unique_film_number_exists = False
            unique_project_roll_exists = False
        
        # Add constraints if they don't exist
        if not unique_film_number_exists:
            # Create the constraint manually for SQLite
            if 'sqlite' in connection.vendor:
                cursor.execute("""
                    CREATE UNIQUE INDEX IF NOT EXISTS unique_film_number 
                    ON microapp_roll(film_number) 
                    WHERE film_number IS NOT NULL
                """)
        
        if not unique_project_roll_exists:
            # Create the constraint manually for SQLite
            if 'sqlite' in connection.vendor:
                cursor.execute("""
                    CREATE UNIQUE INDEX IF NOT EXISTS unique_project_roll_id_film_type 
                    ON microapp_roll(project_id, roll_id, film_type)
                """)


def reverse_add_constraints(apps, schema_editor):
    """Remove constraints if they exist."""
    with connection.cursor() as cursor:
        if 'sqlite' in connection.vendor:
            cursor.execute("DROP INDEX IF EXISTS unique_film_number")
            cursor.execute("DROP INDEX IF EXISTS unique_project_roll_id_film_type")


class Migration(migrations.Migration):

    dependencies = [
        ('microapp', '0026_remove_roll_rework_requested'),
    ]

    operations = [
        # Skip RemoveField - table was already manually dropped
        # Just remove the model from Django's state
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Table already dropped manually, no database operation needed
            ],
            state_operations=[
                migrations.DeleteModel(
                    name='FilmingSessionLog',
                ),
            ],
        ),
        migrations.AlterField(
            model_name='roll',
            name='filming_status',
            field=models.CharField(choices=[('ready', 'Ready to Film'), ('filming', 'Currently Filming'), ('completed', 'Filming Completed'), ('error', 'Filming Error'), ('rework', 'Rework')], default='ready', help_text='Current filming status of this roll', max_length=20),
        ),
        # Add constraints conditionally
        migrations.RunPython(
            add_constraints_if_not_exists,
            reverse_add_constraints,
        ),
        # Update Django state to reflect the constraints
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Constraints already added in RunPython above
            ],
            state_operations=[
                migrations.AddConstraint(
                    model_name='roll',
                    constraint=models.UniqueConstraint(condition=models.Q(('film_number__isnull', False)), fields=('film_number',), name='unique_film_number'),
                ),
                migrations.AddConstraint(
                    model_name='roll',
                    constraint=models.UniqueConstraint(fields=('project', 'roll_id', 'film_type'), name='unique_project_roll_id_film_type'),
                ),
            ],
        ),
    ]
